language: rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: beta
    - env: TARGET=x86_64-unknown-linux-gnu DISABLE_TESTS=1
      rust: nightly
      allow_failures: true
    - env: TARGET=x86_64-apple-darwin DISABLE_TESTS=1
      os: osx
      rust: beta
      allow_failures: true
    - env: TARGET=x86_64-pc-windows-gnu DISABLE_TESTS=1
      os: windows
      rust: beta
      allow_failures: true

before_cache:
  - chmod -R a+r $HOME/.cargo

cache: cargo
  
before_script:
  - rustup self update
  - source ~/.cargo/env || true
  
script:
  - cargo build --all
  - cargo test --verbose --all
  
