language: rust

rust:
  - beta
  - nightly

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-apple-darwin DISABLE_TESTS=1
      os: osx
    - env: TARGET=x86_64-pc-windows-gnu DISABLE_TESTS=1
      os: windows

allow_failures:
  - rust: nightly

before_cache:
  - chmod -R a+r $HOME/.cargo

cache: cargo
  
before_script:
  - rustup self update
  - source ~/.cargo/env || true
  
script:
  - cargo build --all
  - cargo test --verbose --all
  
